policyCheckProject/policyApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.createData, name='create'),
    path('success',views.successpage,name='success')
]

policyCheckProject/policyCheckProject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('policyApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

policyCheckProject/policyApp/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class PolicyModel(models.Model):
  # pass
  # CHOICES = (
  #       ('Sensemaking', 'sensemaking'),
  #       ('Health', 'health'),
  #       ('Education', 'education'),
       
  #   )

  # policy_making_process = models.CharField(max_length=20, choices=CHOICES, default='Sensemaking')
  user_name = models.CharField(max_length=100)
  policy_choice = models.CharField(max_length=100, default="null")
  
  justified_yes = models.BooleanField(default=False)
  justified_no = models.BooleanField(default=False)
  justified_comment = models.TextField()
  justified_file = models.FileField(upload_to='documents/')
  
  redistributive_yes = models.BooleanField(default=False)
  redistributive_no = models.BooleanField(default=False)
  redistributive_comment = models.TextField()
  redistributive_file = models.FileField(upload_to='documents/')
  
  
  practical_yes = models.BooleanField(default=False)
  practical_no = models.BooleanField(default=False)
  practical_comment = models.TextField()
  practical_file = models.FileField(upload_to='documents/')
  
  interventional_yes = models.BooleanField(default=False)
  interventional_no = models.BooleanField(default=False)
  interventional_comment = models.TextField()
  interventional_file = models.FileField(upload_to='documents/')
  
  
  cost_yes = models.BooleanField(default=False)
  cost_no = models.BooleanField(default=False)
  cost_comment = models.TextField()
  cost_file = models.FileField(upload_to='documents/')
  
  
  finance_yes = models.BooleanField(default=False)
  finance_no = models.BooleanField(default=False)
  finance_comment = models.TextField()
  finance_file = models.FileField(upload_to='documents/')
  
  
  def __str__(self):
        return f"{self.user_name} - {self.policy_choice}"
  
  

  

policyCheckProject/policyApp/views.py
# views.py

from django.shortcuts import render, redirect
from .models import PolicyModel

def createData(request):
    if request.method == 'POST':
        # Retrieve form data from the request.POST dictionary
        # policy_making_process = request.POST.get('policy_making_process')
        user_name = request.POST.get('user_name')
        policy_choice = request.POST.get('policy_choice')

        justified_yes = request.POST.get('justified_yes')
        justified_no = request.POST.get('justified_no')
        justified_comment = request.POST.get('justified_comment')
        justified_file = request.FILES.get('justified_file')

        redistributive_yes = request.POST.get('redistributive_yes')
        redistributive_no = request.POST.get('redistributive_no')
        redistributive_comment = request.POST.get('redistributive_comment')
        redistributive_file = request.FILES.get('redistributive_file')

        practical_yes = request.POST.get('practical_yes')
        practical_no = request.POST.get('practical_no')
        practical_comment = request.POST.get('practical_comment')
        practical_file = request.FILES.get('practical_file')

        interventional_yes = request.POST.get('interventional_yes')
        interventional_no = request.POST.get('interventional_no')
        interventional_comment = request.POST.get('interventional_comment')
        interventional_file = request.FILES.get('interventional_file')

        cost_yes = request.POST.get('cost_yes')
        cost_no = request.POST.get('cost_no')
        cost_comment = request.POST.get('cost_comment')
        cost_file = request.FILES.get('cost_file')

        finance_yes = request.POST.get('finance_yes')
        finance_no = request.POST.get('finance_no')
        finance_comment = request.POST.get('finance_comment')
        finance_file = request.FILES.get('finance_file')

        # Create or save your model instance with the form data
        instance = PolicyModel.objects.create(
            # policy_making_process=policy_making_process,
            user_name=user_name,
            policy_choice = policy_choice,

            justified_yes=bool(justified_yes),
            justified_no=bool(justified_no),
            justified_comment=justified_comment,
            justified_file=justified_file,

            redistributive_yes=bool(redistributive_yes),
            redistributive_no=bool(redistributive_no),
            redistributive_comment=redistributive_comment,
            redistributive_file=redistributive_file,

            practical_yes=bool(practical_yes),
            practical_no=bool(practical_no),
            practical_comment=practical_comment,
            practical_file=practical_file,

            interventional_yes=bool(interventional_yes),
            interventional_no=bool(interventional_no),
            interventional_comment=interventional_comment,
            interventional_file=interventional_file,

            cost_yes=bool(cost_yes),
            cost_no=bool(cost_no),
            cost_comment=cost_comment,
            cost_file=cost_file,

            finance_yes=bool(finance_yes),
            finance_no=bool(finance_no),
            finance_comment=finance_comment,
            finance_file=finance_file,
        )
        instance.save()

        # Redirect to a success page or to the admin change view of the created instance
        # For example, redirect to the admin change view of the created instance:
        return redirect('success')

    return render(request, 'index.html')

def successpage(request):
    return render(request,'success.html')

policyCheckProject/policyCheckProject/templates/index.html
{% comment %} {% load static %} {% endcomment %}

<!DOCTYPE html>
<html>
<head>
    <title>Policy Stability Estimator</title>
</head>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Kaushan+Script&family=Poppins&family=Space+Mono&display=swap" rel="stylesheet">
<link rel="icon" type="image/x-icon" href="https://image.shutterstock.com/shutterstock/photos/453787648/display_1500/stock-vector-scales-balance-icon-453787648.jpg">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
<style>

  *{
    font-family: 'Poppins', sans-serif;
  }

  textarea{
    border: none;
    outline: none;
    resize: none;
    
  }
  
  input[type="text"]{
    border: none;
    outline: none;
  }
  
  .yes-no-flex{
    display: flex;
  }
  
  .hide{
    display: none;
  }
  

</style>

<body>
    <div class="container bg-dark pt-3 pb-3 rounded">
    {% comment %} <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'create' %}" >Home</a>
              <a class="nav-link" href="{% url 'success' %}" >Success</a>
              
  
            </div>
          </div>
        </div>
      </nav> {% endcomment %}


 
    <h3 class="display-5 text-center bg-secondary p-3 mb-2 text-white mt-3 rounded">Policy Choice Stability Estimator</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}


        <!-- User Name -->
        <div>
        
        <div class="text-center">
          <h6 class="text-white" style="">Policymaking Process: <span>Sensemaking</span></h6>
        <label for="id_user_name" class="mt-3 text-white">User Name </label>
        <input type="text" name="user_name" id="id_user_name" required class="border border-4 rounded" placeholder="Enter your name"><br>
    
  <div class="d-flex justify-content-center align-items-center mt-4">
    <div class="row form-group">
      <label for="policy_choice" class="mt-3 col-form-label col-md-2.5 text-white">Policy Choice</label>
      <div class="col-md-8"> <!-- Adjust the column width as needed -->
        <textarea class="form-control" name="policy_choice" required id="policy_choice" rows="2" placeholder="Enter policy code"></textarea>
      </div>
    </div>
  </div>
  
      </div>
  </div>
        <!-- Justified -->
        <div class="container ">
            <div class="row">
        <div class="cat-one col-md-4 card">
          <h5 class="bg-light p-2 rounded-pill text-center mt-1">Positional Evidence</h5>
        <p>Policy choice is: </p>
        <h6>1. Justified</h6>
        <div class="yes-no-flex">
        <label for="justified_yes">Yes<input id="justified_yes" type="checkbox"  name="justified_yes" value="Yes" class="evidence_justified check"></label><br>
        <label for="justified_no" class="mx-1" >No<input id="justified_no" type="checkbox" name="justified_no" value="No" class="evidence_justified check"></label><br>
    </div>
        <label for="justified_comment">Comment:</label>
        <textarea required name="justified_comment" id="justified_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="justified_ style="border:none;cursor:pointer;"">File:</label>
        <input type="file" name="justified_file" id="justified_file"><br>

        <!-- Redistributive -->
        <h6>2. Redistributive</h6>
        <div class="yes-no-flex">
        <label for="red_yes">Yes<input id="red_yes" type="checkbox" name="redistributive_yes" value="Yes" class="check"></label><br>
        <label for="red_no" class="mx-1" >No<input id="red_no" type="checkbox" name="redistributive_no" value="No" class="check"></label><br>
        </div>
        <label for="redistributive_comment">Comment:</label>
        <textarea required name="redistributive_comment" id="redistributive_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="redistributive_file">File:</label>
        <input type="file" name="redistributive_file" id="redistributive_file"><br>
        </div>

        <!-- Practical -->
        <div class="cat-two col-md-4 card">
          <h5 class="bg-light p-2 rounded-pill text-center mt-1">Situational Evidence</h5>
            <p>Policy choice is: </p>
        <h6>1. Practical</h6>
        <div class="yes-no-flex">
        <label for="pra_yes">Yes<input id="pra_yes" type="checkbox" name="practical_yes" value="Yes" class="check"></label><br>
        <label for="pra_no" class="mx-1" >No<input id="pra_no" type="checkbox" name="practical_no" value="No" class="check"></label><br>
        </div>
        <label for="practical_comment">Comment:</label>
        <textarea required name="practical_comment" id="practical_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="practical_file">File:</label>
        <input type="file"  name="practical_file" id="practical_file"><br>

        <!-- Interventional -->
        <h6>2. Interventional</h6>
        <div class="yes-no-flex">
        <label for="int_yes">Yes<input id="int_yes" type="checkbox" name="interventional_yes" value="Yes" class="check"></label><br>
        <label for="int_no" class="mx-1" >No<input id="int_no" type="checkbox" name="interventional_no" value="No" class="check"></label><br>
        </div>
        <label for="interventional_comment">Comment:</label>
        <textarea required name="interventional_comment" id="interventional_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="interventional_file">File:</label>
        <input type="file"  name="interventional_file" id="interventional_file"><br>
        </div>
        <!-- Cost -->

        <div class="cat-three col-md-4 card">
          <h5 class="bg-light p-2 rounded-pill text-center mt-1">Value for money Evidence</h5>
            <p>Policy choice is: </p>
        <h6>1. Cost Effective</h6>
        <div class="yes-no-flex">
        <label for="cost_yes">Yes<input id="cost_yes" type="checkbox" name="cost_yes" value="Yes" class="check"></label><br>
        <label for="cost_no" class="mx-1" >No<input id="cost_no" type="checkbox" name="cost_no" value="No" class="check"></label><br>
        </div>
        <label for="cost_comment">Comment:</label>
        <textarea required name="cost_comment" id="cost_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="cost_file">File:</label>
        <input type="file"  name="cost_file" id="cost_file"><br>

        <!-- Finance -->
        <h6>2. Financially Sustainable</h6>
        <div class="yes-no-flex">
        <label for="fin_yes">Yes<input id="fin_yes" type="checkbox" name="finance_yes" value="Yes" class="check"></label><br>
        <label for="fin_no" class="mx-1" >No<input id="fin_no" type="checkbox" name="finance_no" value="No" class="check"></label><br>
        </div>
        <label for="finance_comment">Comment:</label>
        <textarea required name="finance_comment" id="finance_comment" rows="4" cols="50" class="border border-4 rounded"></textarea><br>
        <label for="finance_file">File:</label>
        <input type="file" name="finance_file" id="finance_file"><br>
        </div>
    </div>
</div>
</div>

<div class="d-flex justify-content-center align-items-center mt-4">
        <button type="submit" class="submit btn btn-success">Submit</button>
</div>

{% comment %} calculation part {% endcomment %}

    </form>
    <div class="calculation part">
         
      <div class="charts_calc container text-center">

        <div class="calc_info row">
         <div class="col">
        <div class="calc_value mt-5"></div>

        <div class="result-note"></div>
        

      </div>

      <div class="col">  
        <div id="chartContainer" class="d-flex justify-content-center align-items-center mt-4"></div>
      </div>
      </div>
    
    {% comment %} <div class="col">  
      <div id="chartContainer" class="d-flex justify-content-center align-items-center mt-4"></div>
    </div> {% endcomment %}
    </div>
    </div>
    <div class="d-flex justify-content-center align-items-center mt-4">
    <button class="click-btn btn btn-primary mb-4">Check score</button>
    </div>





    <script>

   // button feature
const btnSubmit = document.querySelector('.btn-success')
btnSubmit.style.display = "none";


      function addCheckboxEventListeners(checkboxYes, checkboxNo) {
        checkboxYes.addEventListener("change", function () {
            if (checkboxYes.checked) {
                checkboxNo.checked = false;
            }
        });
    
        checkboxNo.addEventListener("change", function () {
            if (checkboxNo.checked) {
                checkboxYes.checked = false;
            }
        });
    }
    
    // Get references to the checkbox pairs
    const checkboxPairs = [
        [document.getElementById("justified_yes"), document.getElementById("justified_no")],
        [document.getElementById("red_yes"), document.getElementById("red_no")],
        [document.getElementById("pra_yes"), document.getElementById("pra_no")],
        [document.getElementById("int_yes"), document.getElementById("int_no")],
        [document.getElementById("cost_yes"), document.getElementById("cost_no")],
        [document.getElementById("fin_yes"), document.getElementById("fin_no")]
    ];
    
    // Add event listeners to all checkbox pairs
    checkboxPairs.forEach(pair => {
        addCheckboxEventListeners(pair[0], pair[1]);
    });
    



    let submit = document.querySelector('.submit')
let btn = document.querySelector('.click-btn')
let stable = document.querySelector('.stable')
let unstable = document.querySelector('.unstable')
let body = document.querySelector('body')
let calc_value = document.querySelector('.calc_value')
let check = document.getElementsByClassName("check")

let resultNote = document.querySelector('.result-note')
let divStable = document.createElement('div')
let pStable = document.createElement('p')
let actionStable = document.createElement('h5')
let noteStable = document.createElement('p')




// formula for psc to be calculated
let total_yes_length = document.querySelectorAll('input[value="Yes"]').length;
let total_no_length = document.querySelectorAll('input[value="No"]').length

btn.addEventListener('click',()=>{
  btnSubmit.style.display = "block";
  submit.style.display = 'block'
  let yes_count = 0;
  let no_count = 0;
  for(let i = 0; i < check.length; i++){
    if(check[i].value ==='Yes' && check[i].checked){
      yes_count++
    }else if(check[i].value ==='No' && check[i].checked){
      no_count++
    }
  }

let numerator_value = 7 + (yes_count - no_count)
let denominator_value = 1 + (total_yes_length + total_no_length)

let final_value = Math.ceil((numerator_value / denominator_value) * 100)
console.log(final_value)
calc_value.textContent = `Score: ${(final_value)}%`



if(final_value >=70){
  // stable.style.display = 'block';
  pStable.innerText = "Stable policy choice"
  actionStable.innerText = "Action"
  noteStable.innerText = "May proceed with implementation"
  
  divStable.appendChild(pStable);
  divStable.appendChild(actionStable);
  divStable.appendChild(noteStable);
  divStable.style.backgroundColor ="#5cc019"
  divStable.style.border ="1px solid none"
  divStable.style.color ="whitesmoke"
  divStable.style.fontWeight ="400"
  divStable.style.borderRadius ="5px"
  divStable.style.padding ="7px"
  resultNote.appendChild(divStable)
}else{
  pStable.innerText = "Unstable policy choice"
  actionStable.innerText = "Action"
  noteStable.innerText = "Refine decision or try other options"
  
  divStable.appendChild(pStable);
  divStable.appendChild(actionStable);
  divStable.appendChild(noteStable);
  divStable.style.backgroundColor ="#ff4500"
  divStable.style.border ="1px solid none"
  divStable.style.color ="whitesmoke"
  divStable.style.fontWeight ="400"
  divStable.style.borderRadius ="5px"
  divStable.style.padding ="7px"
  resultNote.appendChild(divStable)
}
 console.log(`yes: ${yes_count}, no:${no_count}`)
 getChart(yes_count,no_count)
})

//  Drawing charts
function getChart(yes_count,no_count){
  google.charts.load('current', { 'packages': ['corechart'] });
  google.charts.setOnLoadCallback(drawChart);
  function drawChart(){
    let data = google.visualization.arrayToDataTable([
      ['Reply', 'Count',{ role: 'style' }],
      ['Yes', yes_count,'#00f'],
      ['No', no_count,'#f00']
    ]);

    const options = {
      title: 'Policy Choice Stability Check',
      width: 500,
      height: 300,
      legend: 'none',
      bars: 'vertical',
      hAxis: {
        title: 'Replies'
      },
      vAxis: {
        title: 'Count'
      },
    };
  let chart = new google.visualization.ColumnChart(document.getElementById('chartContainer'));
  chart.draw(data, options);
  }
}

      


    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://www.gstatic.com/charts/loader.js"></script>
{% comment %} <script src="{% static 'js/script.js' %}"></script> {% endcomment %}
</body>
</html>

policyCheckProject/policyCheckProject/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Kaushan+Script&family=Poppins&family=Space+Mono&display=swap" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="https://image.shutterstock.com/shutterstock/photos/453787648/display_1500/stock-vector-scales-balance-icon-453787648.jpg">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Document</title>

  <style>

    *{
      font-family: 'Poppins', sans-serif;
    }
  </style>
</head>
<body>
 
  {% comment %} <a class="nav-link" href="{% url 'success' %}" >Success</a> {% endcomment %}
  <div class="d-flex justify-content-center align-items-center mt-4 vh-100">
  <div class="card" style="width: 30rem;">
    <div class="card-body text-center">
      <h3 class="card-title">Data submitted successfully!</h3>
     
     <button class="btn"><a href="{% url 'create' %}"  class="btn btn-primary">Home</a></button>
     <button class="btn"><a href="https://www.google.com/" target="_blank"  class="btn btn-danger">Exit</a></button>
      
    </div>
  </div>
</div>







  
 
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>